//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntittyFramewordWebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int empId { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public double salary { get; set; }
        public int deptno { get; set; }
    }
}
